version: '2'
services:
  db:
    build:
      context: ./db-server
    env_file:
      - ./db-server/.env
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5437:5432'
    restart: always
volumes:
  db-data:
    external:
      name: cam-db-data